spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

server:
  port: 8080

rabbitmq:
  exchange: example-exchange
  queue: example-queue
  routingkey: example-routingkey