spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest


rabbitmq:
  direct:
    exchange: direct-exchange
    queue: direct-queue
    route1: direct-route-one
    route2 : direct-route-two
  topic:
    exchange: topic-exchange
  fanout:
    exchange: fanout-exchange

messaging:
  direct:
    enabled: false
  topic:
    enabled: false
  fanout:
    enabled: true

server:
  port: 8080