spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual


rabbitmq:
  direct:
    exchange: direct-exchange
    queue: direct-queue-2
    route1: direct-route-one
    route2 : direct-route-two
  topic:
    exchange: topic-exchange
    queue: topic-queue2
  fanout:
    exchange: fanout-exchange
    exchange-reply: fanout-exchange-reply
    queue: fanout-queue-subscriber-two

messaging:
  direct:
    enabled: false
  topic:
    enabled: false
  fanout:
    enabled: true

server:
  port: 8083